/* Artifact: mqtt
 * Agent <-> Artifact <-> Node-RED <-> MQTT Broker <-> Thing
 */

package net;

import cartago.*;
import jason.asSyntax.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class MQTTArt extends jacamo.rest.util.DummyArt {

    public void init(String endpoint) {
        // Observable properties perceived by the Jason agent.
        defineObsProperty("request", "target", "operation", "data");
        defineObsProperty("report", "device", "property", "value");
        defineObsProperty("event", "device", "event", "data");
        super.register(endpoint);
    }

    // Communication: receives a request addressed to the agent.
    @OPERATION
    public void communication(String json) { // request(Target, Operation, Data)
	JsonObject obj = new JsonParser().parse(json).getAsJsonObject();
	String target = obj.get("target").getAsString();
        String operation = obj.get("operation").getAsString();
        JsonElement data = obj.get("data");
	getObsProperty("request").updateValues(stringToAtom(target),stringToAtom(operation),jsonValueToTerm(data));
    }

    // Reporting: Reporting: receives a Property value reported by a Thing.
    @OPERATION
    public void reporting(String json) { // report(Thing, Property, Value)
	JsonObject obj = new JsonParser().parse(json).getAsJsonObject();
	String thing = obj.get("thing").getAsString();
        String property = obj.get("property").getAsString();
	JsonElement value = obj.get("value");
	getObsProperty("report").updateValues(stringToAtom(thing),stringToAtom(property),jsonValueToTerm(value));
    }

    // Monitoring: Monitoring: receives an Event notification generated by a Thing.
    @OPERATION
    public void monitoring(String json) { // event(Thing, Event, Data)
        JsonObject obj = new JsonParser().parse(json).getAsJsonObject();
	String thing = obj.get("thing").getAsString();
        String event = obj.get("event").getAsString();
        JsonElement data = obj.get("data");
        getObsProperty("event").updateValues(stringToAtom(thing),stringToAtom(event),jsonValueToTerm(data));
    }

    // Acting: Acting: receives an action generated by the agent and delegates its execution to the mechanism provided by DummyArt.
    @OPERATION
    public void acting(String action) { // action(Thing, Action, Input)
        try {
            OpFeedbackParam<Term> result = new OpFeedbackParam<Term>();
            act(action, result);
        } catch (Exception e) {
            e.printStackTrace();
            failed("[MQTTArt] Error operation acting: " + e.getMessage());
        }
    }

    // Converts JSON values into Jason terms while preserving numeric and boolean values and representing strings as atoms.
    private Term jsonValueToTerm(JsonElement value) {
	    if (value == null || value.isJsonNull()) {
		return ASSyntax.createAtom("null");
	    }
	    if (value.isJsonPrimitive()) {
		if (value.getAsJsonPrimitive().isBoolean()) {
		    return ASSyntax.createAtom(value.getAsBoolean() ? "true" : "false");
		}
		if (value.getAsJsonPrimitive().isNumber()) {
			return ASSyntax.createNumber(value.getAsDouble());
		}
		String stringValue = value.getAsString();
		return ASSyntax.createAtom(stringValue);
	    }
	    // Structured JSON values are preserved as a Jason string.
	    return ASSyntax.createString(value.toString());
    }

    private Term stringToAtom(String value) {
            return ASSyntax.createAtom(value);
    }
}
